### ISSUE TITLE
Tendermint Client

### ISSUE THREAD

**Issue by mappum** [nomic-io/orga#17]
We can implement the `Read` trait for a client which queries Tendermint RPC. This isn't a `Store` since it's read-only, but is useful for client logic which only needs to read.

This could be a struct called something like `TendermintClient` which would probably belong in the `abci` module since that's where all the Tendermint-specific stuff lives.
```rust
let client = TendermintClient::new("localhost:26657").unwrap();
```

**Comment by mappum** [comment]
This should probably use the `tendermint` crate's RPC client, but if that is having issues we can just implement our own for now (since this only needs the `abci_query` endpoint).

**Comment by cyntran** [comment]
Created merk client too. :+1:
