### ISSUE TITLE
Implement State for Option<T>

### ISSUE THREAD

**Issue by cwlittle** [nomic-io/orga#77]
There are a few patterns where it's more space efficient to only hold certain data on a State struct when configured to use that data. For instance in the original BitcoinSPV collection, there is an option to index the collection by hashes. In reimplementing this, there would need to be another collection to house the mapping between hashes and keys. However, when this feature is not configured, it doesn't make sense to lug around the overhead of that collection, expend the extra cycles in the State struct constructor, or drastically increase the length of the encoded bytes that will be stored in Merk. Implementing State for Option<T> allows to instead hold None when these collections aren't in use and bypass the overhead.

**Comment by mappum** [comment]
Closed in favor of creating an `orga::Option` someday
